"""

Module that reads and writes the per-world tags.yaml file.

That file lists which ArUco markers a world contains and where each one is
placed. The CLI creates it with placeholder poses, and the user edits it by
hand with the real coordinates before generating the world.

The file is written by hand (not with yaml.safe_dump) so it can carry a
header explaining every field to whoever opens it.

Author: Imad Jared Cabrera Trejo
Contact: cabreratrejoimadjared@gmail.com
Team: VespoUAV

"""

import yaml

from aruco_paths import get_tags_config_path, get_world_dir

# Pose used for a marker that has just been added and has not been placed yet.
# Everything at zero on purpose: it is obviously a placeholder, so nobody
# mistakes it for a real coordinate.
DEFAULT_POSE = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# Header written at the top of every generated tags.yaml
YAML_HEADER = """# ---------------------------------------------------------------------------
# VespoUAV - ArUco tag placement for world '{world_name}'
#
# This file says WHICH markers the world contains and WHERE each one goes.
# It is generated by aruco_generator.py and meant to be edited by hand.
#
#   id    the ArUco marker ID. Its model must exist in models/aruco_markers/
#   pose  [x, y, z, roll, pitch, yaw]
#         x, y, z in meters, roll/pitch/yaw in radians.
#         A pose of all zeros means the marker has NOT been placed yet.
#
# Reminder: a marker lying flat on the floor needs no rotation. A marker on a
# wall needs roll = 1.5708 (90 degrees), and yaw decides which way it faces.
#
# WARNING: re-running aruco_generator.py rewrites this file. Existing poses are
# preserved, but any comment you add below this header will be lost.
# ---------------------------------------------------------------------------

markers:
"""


def read_tags_config(world_name):
    """
    Reads the tags.yaml of a world and returns a dict mapping marker ID to pose.

    Returns an empty dict if the file does not exist yet, so callers can treat
    a brand new world and an empty one the same way.

    Parameters:
    - world_name: name of the world, e.g. 'practice'
    """
    config_path = get_tags_config_path(world_name)

    if not config_path.is_file():
        return {}

    content = config_path.read_text(encoding="utf-8")

    # safe_load and not load: load can execute arbitrary code from the file
    data = yaml.safe_load(content)

    # An empty or malformed file parses to None, treat it as no markers
    if not data or "markers" not in data or not data["markers"]:
        return {}

    # Turn the list of dicts into a {id: pose} dict, which is much easier to merge
    poses = {}
    for entry in data["markers"]:
        poses[entry["id"]] = entry.get("pose", DEFAULT_POSE)

    return poses


def write_tags_config(world_name, marker_ids):
    """
    Writes the tags.yaml of a world, merging with whatever is already there.

    Markers already present keep the pose the user edited. Markers in
    marker_ids that are not in the file yet are added with DEFAULT_POSE.
    Markers already in the file are never removed.

    Parameters:
    - world_name: name of the world, e.g. 'practice'
    - marker_ids: list of marker IDs that should be present in the world

    Returns the list of IDs that were newly added.
    """
    # Whatever the user already placed by hand
    existing_poses = read_tags_config(world_name)

    # Only the IDs we do not know about yet get a placeholder pose
    new_ids = [marker_id for marker_id in marker_ids if marker_id not in existing_poses]

    for marker_id in new_ids:
        existing_poses[marker_id] = DEFAULT_POSE

    # Sorted so the file has a stable order and diffs stay readable
    lines = [YAML_HEADER.format(world_name=world_name)]
    for marker_id in sorted(existing_poses):
        pose = existing_poses[marker_id]
        pose_text = ", ".join(str(value) for value in pose)
        lines.append(f"  - id: {marker_id}\n")
        lines.append(f"    pose: [{pose_text}]\n")

    # The world folder may not exist on a brand new world
    get_world_dir(world_name).mkdir(parents=True, exist_ok=True)

    config_path = get_tags_config_path(world_name)
    config_path.write_text("".join(lines), encoding="utf-8")

    return new_ids